/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YoutubersYoutuberIdRouteImport } from './routes/youtubers.$youtuberId'
import { Route as SponsorsSponsorIdRouteImport } from './routes/sponsors.$sponsorId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubersYoutuberIdRoute = YoutubersYoutuberIdRouteImport.update({
  id: '/youtubers/$youtuberId',
  path: '/youtubers/$youtuberId',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsSponsorIdRoute = SponsorsSponsorIdRouteImport.update({
  id: '/sponsors/$sponsorId',
  path: '/sponsors/$sponsorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sponsors/$sponsorId': typeof SponsorsSponsorIdRoute
  '/youtubers/$youtuberId': typeof YoutubersYoutuberIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sponsors/$sponsorId': typeof SponsorsSponsorIdRoute
  '/youtubers/$youtuberId': typeof YoutubersYoutuberIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sponsors/$sponsorId': typeof SponsorsSponsorIdRoute
  '/youtubers/$youtuberId': typeof YoutubersYoutuberIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sponsors/$sponsorId'
    | '/youtubers/$youtuberId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sponsors/$sponsorId'
    | '/youtubers/$youtuberId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sponsors/$sponsorId'
    | '/youtubers/$youtuberId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SponsorsSponsorIdRoute: typeof SponsorsSponsorIdRoute
  YoutubersYoutuberIdRoute: typeof YoutubersYoutuberIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtubers/$youtuberId': {
      id: '/youtubers/$youtuberId'
      path: '/youtubers/$youtuberId'
      fullPath: '/youtubers/$youtuberId'
      preLoaderRoute: typeof YoutubersYoutuberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/$sponsorId': {
      id: '/sponsors/$sponsorId'
      path: '/sponsors/$sponsorId'
      fullPath: '/sponsors/$sponsorId'
      preLoaderRoute: typeof SponsorsSponsorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SponsorsSponsorIdRoute: SponsorsSponsorIdRoute,
  YoutubersYoutuberIdRoute: YoutubersYoutuberIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
