name = "sponsorspy-crawler"
main = "dist/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = ""
workers_dev = true

[env.development]
routes = []
